package com.cuzz.rookieteam.mapper;

import com.cuzz.rookieteam.model.TeamPlayer;
import com.cuzz.rookieteam.model.TeamPlayerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TeamPlayerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rookieteam_players
     *
     * @mbggenerated Mon Apr 14 20:40:27 CST 2025
     */
    int countByExample(TeamPlayerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rookieteam_players
     *
     * @mbggenerated Mon Apr 14 20:40:27 CST 2025
     */
    int deleteByExample(TeamPlayerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rookieteam_players
     *
     * @mbggenerated Mon Apr 14 20:40:27 CST 2025
     */
    int deleteByPrimaryKey(String playerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rookieteam_players
     *
     * @mbggenerated Mon Apr 14 20:40:27 CST 2025
     */
    int insert(TeamPlayer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rookieteam_players
     *
     * @mbggenerated Mon Apr 14 20:40:27 CST 2025
     */
    int insertSelective(TeamPlayer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rookieteam_players
     *
     * @mbggenerated Mon Apr 14 20:40:27 CST 2025
     */
    List<TeamPlayer> selectByExample(TeamPlayerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rookieteam_players
     *
     * @mbggenerated Mon Apr 14 20:40:27 CST 2025
     */
    TeamPlayer selectByPrimaryKey(String playerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rookieteam_players
     *
     * @mbggenerated Mon Apr 14 20:40:27 CST 2025
     */
    int updateByExampleSelective(@Param("record") TeamPlayer record, @Param("example") TeamPlayerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rookieteam_players
     *
     * @mbggenerated Mon Apr 14 20:40:27 CST 2025
     */
    int updateByExample(@Param("record") TeamPlayer record, @Param("example") TeamPlayerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rookieteam_players
     *
     * @mbggenerated Mon Apr 14 20:40:27 CST 2025
     */
    int updateByPrimaryKeySelective(TeamPlayer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rookieteam_players
     *
     * @mbggenerated Mon Apr 14 20:40:27 CST 2025
     */
    int updateByPrimaryKey(TeamPlayer record);
}