package com.cuzz.rookieteam.model;

import java.util.Date;

public class Team {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rookieteam_teams.team_id
     *
     * @mbggenerated Mon Apr 14 20:40:27 CST 2025
     */
    private Integer teamId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rookieteam_teams.team_name
     *
     * @mbggenerated Mon Apr 14 20:40:27 CST 2025
     */
    private String teamName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rookieteam_teams.leader_id
     *
     * @mbggenerated Mon Apr 14 20:40:27 CST 2025
     */
    private String leaderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rookieteam_teams.create_time
     *
     * @mbggenerated Mon Apr 14 20:40:27 CST 2025
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rookieteam_teams.level
     *
     * @mbggenerated Mon Apr 14 20:40:27 CST 2025
     */
    private Integer level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rookieteam_teams.experience
     *
     * @mbggenerated Mon Apr 14 20:40:27 CST 2025
     */
    private Integer experience;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rookieteam_teams.total_damage
     *
     * @mbggenerated Mon Apr 14 20:40:27 CST 2025
     */
    private Long totalDamage;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rookieteam_teams.team_id
     *
     * @return the value of rookieteam_teams.team_id
     *
     * @mbggenerated Mon Apr 14 20:40:27 CST 2025
     */
    public Integer getTeamId() {
        return teamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rookieteam_teams.team_id
     *
     * @param teamId the value for rookieteam_teams.team_id
     *
     * @mbggenerated Mon Apr 14 20:40:27 CST 2025
     */
    public void setTeamId(Integer teamId) {
        this.teamId = teamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rookieteam_teams.team_name
     *
     * @return the value of rookieteam_teams.team_name
     *
     * @mbggenerated Mon Apr 14 20:40:27 CST 2025
     */
    public String getTeamName() {
        return teamName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rookieteam_teams.team_name
     *
     * @param teamName the value for rookieteam_teams.team_name
     *
     * @mbggenerated Mon Apr 14 20:40:27 CST 2025
     */
    public void setTeamName(String teamName) {
        this.teamName = teamName == null ? null : teamName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rookieteam_teams.leader_id
     *
     * @return the value of rookieteam_teams.leader_id
     *
     * @mbggenerated Mon Apr 14 20:40:27 CST 2025
     */
    public String getLeaderId() {
        return leaderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rookieteam_teams.leader_id
     *
     * @param leaderId the value for rookieteam_teams.leader_id
     *
     * @mbggenerated Mon Apr 14 20:40:27 CST 2025
     */
    public void setLeaderId(String leaderId) {
        this.leaderId = leaderId == null ? null : leaderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rookieteam_teams.create_time
     *
     * @return the value of rookieteam_teams.create_time
     *
     * @mbggenerated Mon Apr 14 20:40:27 CST 2025
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rookieteam_teams.create_time
     *
     * @param createTime the value for rookieteam_teams.create_time
     *
     * @mbggenerated Mon Apr 14 20:40:27 CST 2025
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rookieteam_teams.level
     *
     * @return the value of rookieteam_teams.level
     *
     * @mbggenerated Mon Apr 14 20:40:27 CST 2025
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rookieteam_teams.level
     *
     * @param level the value for rookieteam_teams.level
     *
     * @mbggenerated Mon Apr 14 20:40:27 CST 2025
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rookieteam_teams.experience
     *
     * @return the value of rookieteam_teams.experience
     *
     * @mbggenerated Mon Apr 14 20:40:27 CST 2025
     */
    public Integer getExperience() {
        return experience;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rookieteam_teams.experience
     *
     * @param experience the value for rookieteam_teams.experience
     *
     * @mbggenerated Mon Apr 14 20:40:27 CST 2025
     */
    public void setExperience(Integer experience) {
        this.experience = experience;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rookieteam_teams.total_damage
     *
     * @return the value of rookieteam_teams.total_damage
     *
     * @mbggenerated Mon Apr 14 20:40:27 CST 2025
     */
    public Long getTotalDamage() {
        return totalDamage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rookieteam_teams.total_damage
     *
     * @param totalDamage the value for rookieteam_teams.total_damage
     *
     * @mbggenerated Mon Apr 14 20:40:27 CST 2025
     */
    public void setTotalDamage(Long totalDamage) {
        this.totalDamage = totalDamage;
    }
}