name: RookieTeam
version: '1.0-SNAPSHOT'
main: com.cuzz.rookieteam.RookieTeam
api-version: '1.21.4'
commands:
  rteam:
    description: RookieTeam Command
    permission: rookieteam.use
    permission-message: 你没有权限使用此命令。